name: Reusable_workflow1
on: [workflow_call]
jobs:

  workspace_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: cleaning the workspace 
        run: rm -rf * $GITHUB_WORKSPACE/*

  code_checkout:
    runs-on: ubuntu-latest
    needs: workspace_cleanup
    
    steps:
      - name: code checkout
        uses: actions/checkout@v4
  
  build:
    needs: code_checkout
    runs-on: ubuntu-latest
    steps:
      - name: java install
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle


      - name: Verify Files
        run: |
          pwd
          ls -ltr

      - name: verify gradle
        run: |
          gradle -v

     # - name: Make Gradle Wrapper Executable
     #   run: chmod +x gradlew    


      #- name: buiding the application
       # run: |
       #   ./gradlew clean bootJar 

